### ISSUE TITLE
Модуль з права

### ISSUE THREAD

**Issue by Taras17** [Taras17/Law#1]
Давайте обговоримо питання на модуль з права.

**Comment by IlonaSofianidi** [comment]
@Taras17 які теми буде охоплювати модуль?

**Comment by Taras17** [comment]
@IlonaSofianidi 1) Міжнародне космічне право;
2) Міжнародне кримінальне право;

**Comment by IlonaSofianidi** [comment]
О,дякую велике

**Comment by IlonaSofianidi** [comment]
Щось можливо підготувати потрібно? @Taras17

**Comment by Taras17** [comment]
@IlonaSofianidi Якщо хочеш можеш написати ще есе.
