### ISSUE TITLE
Модуль Англ

### ISSUE THREAD

**Issue by IlonaSofianidi** [Taras17/Law#2]
Обговорення тесту з англ. який відбудеться в четвер

**Comment by Taras17** [comment]
Тест має бути тільки по бізнесу, чи по граматиці?

**Comment by IlonaSofianidi** [comment]
По граматиці ,але ми розділені будемо на дві групи .Обери групу в якій ти будеш

**Comment by Taras17** [comment]
Зрозуміло, дуже тобі дякую))
