### ISSUE TITLE
Automatization Issue

### ISSUE THREAD

**Issue by Taras17** [Taras17/Law#4]
Налаштування автоматизації

**Comment by IlonaSofianidi** [comment]
Ми Використати шаблон без автоматизації, потім ти вручну створив колонки ,і додав автоматизацію ?Це все ?

**Comment by Taras17** [comment]
Я ще попереміщав колонки і додав записки та деякі Issue

**Comment by IlonaSofianidi** [comment]
Тоді закриваємо проект ?

**Comment by Taras17** [comment]
Так
